// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAddon = "addons"

// Addon mapped from table <addons>
type Addon struct {
	ID               int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name             string         `gorm:"column:name;not null" json:"name"`
	UniqueIdentifier string         `gorm:"column:unique_identifier;not null" json:"unique_identifier"`
	Version          string         `gorm:"column:version" json:"version"`
	Status           int32          `gorm:"column:status;not null" json:"status"`
	About            string         `gorm:"column:about" json:"about"`
	CreatedAt        time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Addon's table name
func (*Addon) TableName() string {
	return TableNameAddon
}
