// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCertificate = "certificates"

// Certificate mapped from table <certificates>
type Certificate struct {
	ID           int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StudentID    int32          `gorm:"column:student_id" json:"student_id"`
	CourseID     int32          `gorm:"column:course_id" json:"course_id"`
	ShareableURL string         `gorm:"column:shareable_url" json:"shareable_url"`
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Certificate's table name
func (*Certificate) TableName() string {
	return TableNameCertificate
}
