// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCiSession = "ci_sessions"

// CiSession mapped from table <ci_sessions>
type CiSession struct {
	ID        string         `gorm:"column:id;not null" json:"id"`
	IPAddress string         `gorm:"column:ip_address;not null" json:"ip_address"`
	Timestamp int32          `gorm:"column:timestamp;not null" json:"timestamp"`
	Data      []byte         `gorm:"column:data;not null" json:"data"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName CiSession's table name
func (*CiSession) TableName() string {
	return TableNameCiSession
}
