// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID              int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Body            string         `gorm:"column:body" json:"body"`
	UserID          int32          `gorm:"column:user_id" json:"user_id"`
	CommentableID   int32          `gorm:"column:commentable_id" json:"commentable_id"`
	CommentableType string         `gorm:"column:commentable_type" json:"commentable_type"`
	DateAdded       int32          `gorm:"column:date_added" json:"date_added"`
	LastModified    int32          `gorm:"column:last_modified" json:"last_modified"`
	CreatedAt       time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
