// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCompany = "company"

// Company mapped from table <company>
type Company struct {
	ID             int32  `gorm:"column:id;not null" json:"id"`
	Name           string `gorm:"column:name" json:"name"`
	Address        string `gorm:"column:address" json:"address"`
	BounghtCourses string `gorm:"column:bounght_courses;not null" json:"bounght_courses"`
}

// TableName Company's table name
func (*Company) TableName() string {
	return TableNameCompany
}
