// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCourse = "course"

// Course mapped from table <course>
type Course struct {
	ID                     int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SchoolID               int32          `gorm:"column:school_id;not null" json:"school_id"`
	Title                  string         `gorm:"column:title" json:"title"`
	ShortDescription       string         `gorm:"column:short_description" json:"short_description"`
	Description            string         `gorm:"column:description" json:"description"`
	Outcomes               string         `gorm:"column:outcomes" json:"outcomes"`
	Language               string         `gorm:"column:language" json:"language"`
	CategoryID             int32          `gorm:"column:category_id" json:"category_id"`
	SubCategoryID          int32          `gorm:"column:sub_category_id" json:"sub_category_id"`
	Requirements           string         `gorm:"column:requirements" json:"requirements"`
	Price                  float64        `gorm:"column:price" json:"price"`
	DiscountFlag           int32          `gorm:"column:discount_flag" json:"discount_flag"`
	DiscountedPrice        int32          `gorm:"column:discounted_price" json:"discounted_price"`
	Level                  string         `gorm:"column:level" json:"level"`
	UserID                 int32          `gorm:"column:user_id" json:"user_id"`
	Thumbnail              string         `gorm:"column:thumbnail" json:"thumbnail"`
	VideoURL               string         `gorm:"column:video_url" json:"video_url"`
	DateAdded              int32          `gorm:"column:date_added" json:"date_added"`
	LastModified           int32          `gorm:"column:last_modified" json:"last_modified"`
	Visibility             int32          `gorm:"column:visibility" json:"visibility"`
	IsTopCourse            int32          `gorm:"column:is_top_course" json:"is_top_course"`
	IsAdmin                int32          `gorm:"column:is_admin" json:"is_admin"`
	Status                 string         `gorm:"column:status" json:"status"`
	CourseOverviewProvider string         `gorm:"column:course_overview_provider" json:"course_overview_provider"`
	MetaKeywords           string         `gorm:"column:meta_keywords" json:"meta_keywords"`
	MetaDescription        string         `gorm:"column:meta_description" json:"meta_description"`
	IsFreeCourse           int32          `gorm:"column:is_free_course" json:"is_free_course"`
	CreatedAt              time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt              time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt              gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Category               Category       `gorm:"foreignKey:CategoryID" json:"category"`
	Section                []Section      `gorm:"foreignKey:CourseID" json:"section"`
}

// TableName Course's table name
func (*Course) TableName() string {
	return TableNameCourse
}
