// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCurrency = "currency"

// Currency mapped from table <currency>
type Currency struct {
	ID                int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name              string         `gorm:"column:name" json:"name"`
	Code              string         `gorm:"column:code" json:"code"`
	Symbol            string         `gorm:"column:symbol" json:"symbol"`
	PaypalSupported   int32          `gorm:"column:paypal_supported" json:"paypal_supported"`
	StripeSupported   int32          `gorm:"column:stripe_supported" json:"stripe_supported"`
	PaystackSupported int32          `gorm:"column:paystack_supported;not null;default:1" json:"paystack_supported"`
	CreatedAt         time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Currency's table name
func (*Currency) TableName() string {
	return TableNameCurrency
}
