// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameEnrol = "enrol"

// Enrol mapped from table <enrol>
type Enrol struct {
	ID           int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID       int32          `gorm:"column:user_id" json:"user_id"`
	CourseID     int32          `gorm:"column:course_id" json:"course_id"`
	DateAdded    int32          `gorm:"column:date_added" json:"date_added"`
	LastModified int32          `gorm:"column:last_modified" json:"last_modified"`
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Enrol's table name
func (*Enrol) TableName() string {
	return TableNameEnrol
}
