// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLiveClass = "live_class"

// LiveClass mapped from table <live_class>
type LiveClass struct {
	ID                  int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CourseID            int32          `gorm:"column:course_id" json:"course_id"`
	Date                int32          `gorm:"column:date" json:"date"`
	Time                int32          `gorm:"column:time" json:"time"`
	ZoomMeetingID       string         `gorm:"column:zoom_meeting_id" json:"zoom_meeting_id"`
	ZoomMeetingPassword string         `gorm:"column:zoom_meeting_password" json:"zoom_meeting_password"`
	NoteToStudents      string         `gorm:"column:note_to_students" json:"note_to_students"`
	CreatedAt           time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt           time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt           gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName LiveClass's table name
func (*LiveClass) TableName() string {
	return TableNameLiveClass
}
