// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMessageThread = "message_thread"

// MessageThread mapped from table <message_thread>
type MessageThread struct {
	ID                   int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MessageThreadCode    string         `gorm:"column:message_thread_code" json:"message_thread_code"`
	Sender               string         `gorm:"column:sender" json:"sender"`
	Receiver             string         `gorm:"column:receiver" json:"receiver"`
	LastMessageTimestamp string         `gorm:"column:last_message_timestamp" json:"last_message_timestamp"`
	CreatedAt            time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt            time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt            gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName MessageThread's table name
func (*MessageThread) TableName() string {
	return TableNameMessageThread
}
