// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePayment = "payment"

// Payment mapped from table <payment>
type Payment struct {
	ID                      int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID                  int32          `gorm:"column:user_id" json:"user_id"`
	PaymentType             string         `gorm:"column:payment_type" json:"payment_type"`
	TpPaymentTransID        int32          `gorm:"column:tp_payment_trans_id;not null" json:"tp_payment_trans_id"` // compare with banks trans id
	CourseID                int32          `gorm:"column:course_id" json:"course_id"`
	Amount                  float64        `gorm:"column:amount" json:"amount"`
	DateAdded               int32          `gorm:"column:date_added" json:"date_added"`
	LastModified            int32          `gorm:"column:last_modified" json:"last_modified"`
	AdminRevenue            string         `gorm:"column:admin_revenue" json:"admin_revenue"`
	InstructorRevenue       string         `gorm:"column:instructor_revenue" json:"instructor_revenue"`
	InstructorPaymentStatus int32          `gorm:"column:instructor_payment_status" json:"instructor_payment_status"`
	CreatedAt               time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt               time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt               gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Payment's table name
func (*Payment) TableName() string {
	return TableNamePayment
}
