// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameQuestion = "question"

// Question mapped from table <question>
type Question struct {
	ID             int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	QuizID         int32          `gorm:"column:quiz_id" json:"quiz_id"`
	Title          string         `gorm:"column:title" json:"title"`
	Type           string         `gorm:"column:type" json:"type"`
	Options        string         `gorm:"column:options" json:"options"`
	CorrectAnswers string         `gorm:"column:correct_answers" json:"correct_answers"`
	Order          int32          `gorm:"column:order;not null" json:"order"`
	CreatedAt      time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Question's table name
func (*Question) TableName() string {
	return TableNameQuestion
}
