// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRating = "rating"

// Rating mapped from table <rating>
type Rating struct {
	ID           int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Rating       float64        `gorm:"column:rating" json:"rating"`
	UserID       int32          `gorm:"column:user_id" json:"user_id"`
	RatableID    int32          `gorm:"column:ratable_id" json:"ratable_id"`
	RatableType  string         `gorm:"column:ratable_type" json:"ratable_type"`
	DateAdded    int32          `gorm:"column:date_added" json:"date_added"`
	LastModified int32          `gorm:"column:last_modified" json:"last_modified"`
	Review       string         `gorm:"column:review" json:"review"`
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Rating's table name
func (*Rating) TableName() string {
	return TableNameRating
}
