// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSchool = "school"

// School mapped from table <school>
type School struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string `gorm:"column:name;not null" json:"name"`
	Country      string `gorm:"column:country" json:"country"`
	Province     string `gorm:"column:province;not null" json:"province"`
	City         string `gorm:"column:city;not null" json:"city"`
	Line1        string `gorm:"column:line1" json:"line1"`
	Line2        string `gorm:"column:line2" json:"line2"`
	Line3        string `gorm:"column:line3" json:"line3"`
	Address      string `gorm:"column:address" json:"address"`
	Phone1       string `gorm:"column:phone1" json:"phone1"`
	Phone2       string `gorm:"column:phone2" json:"phone2"`
	Email        string `gorm:"column:email" json:"email"`
	BankDetailID int32  `gorm:"column:bank_detail_id" json:"bank_detail_id"`
}

// TableName School's table name
func (*School) TableName() string {
	return TableNameSchool
}
