// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSection = "section"

// Section mapped from table <section>
type Section struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title     string         `gorm:"column:title" json:"title"`
	CourseID  int32          `gorm:"column:course_id;not null" json:"course_id"`
	Order     int32          `gorm:"column:order;not null" json:"order"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Courses   Course         `gorm:"foreignKey:CourseID" json:"courses"`
	Lesson    []Lesson       `gorm:"foreignKey:SectionID" json:"lesson"`
}

// TableName Section's table name
func (*Section) TableName() string {
	return TableNameSection
}
