// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStudentManager = "student_manager"

// StudentManager mapped from table <student_manager>
type StudentManager struct {
	ID        int32 `gorm:"column:id;not null" json:"id"`
	UserID    int32 `gorm:"column:user_id;not null" json:"user_id"`
	CompanyID int32 `gorm:"column:company_id;not null" json:"company_id"`
}

// TableName StudentManager's table name
func (*StudentManager) TableName() string {
	return TableNameStudentManager
}
