// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTag = "tag"

// Tag mapped from table <tag>
type Tag struct {
	ID           int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Tag          string         `gorm:"column:tag" json:"tag"`
	TagableID    int32          `gorm:"column:tagable_id" json:"tagable_id"`
	TagableType  string         `gorm:"column:tagable_type" json:"tagable_type"`
	DateAdded    int32          `gorm:"column:date_added" json:"date_added"`
	LastModified int32          `gorm:"column:last_modified" json:"last_modified"`
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
