// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID               int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type             int32          `gorm:"column:type;default:3" json:"type"`            // 1=Admin, 2=Instructor, 3=Student
	IsRequest        int32          `gorm:"column:is_request;not null" json:"is_request"` // 1=Request Sent,0=Not Requested
	FirstName        string         `gorm:"column:first_name" json:"first_name"`
	LastName         string         `gorm:"column:last_name" json:"last_name"`
	Email            string         `gorm:"column:email" json:"email"`
	Name             string         `gorm:"column:name" json:"name"`
	Password         string         `gorm:"column:password" json:"password"`
	SocialLinks      string         `gorm:"column:social_links" json:"social_links"`
	Biography        string         `gorm:"column:biography" json:"biography"`
	RoleID           int32          `gorm:"column:role_id" json:"role_id"`
	DateAdded        int32          `gorm:"column:date_added" json:"date_added"`
	LastModified     int32          `gorm:"column:last_modified" json:"last_modified"`
	WatchHistory     string         `gorm:"column:watch_history" json:"watch_history"`
	Wishlist         string         `gorm:"column:wishlist" json:"wishlist"`
	Title            string         `gorm:"column:title" json:"title"`
	PaypalKeys       string         `gorm:"column:paypal_keys" json:"paypal_keys"`
	StripeKeys       string         `gorm:"column:stripe_keys" json:"stripe_keys"`
	VerificationCode string         `gorm:"column:verification_code" json:"verification_code"`
	Status           int32          `gorm:"column:status" json:"status"` // 1=Active,0=Pending
	CreatedAt        time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
